//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Npce_WinClient.Test.References.Vol {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS", ConfigurationName="References.Vol.Visure")]
    public interface Visure {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/Invio", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/InvioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WatermarkObject))]
        Npce_WinClient.Test.References.Vol.InvioResult Invio(Npce_WinClient.Test.References.Vol.InvioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/Invio", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/InvioResponse")]
        System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.InvioResult> InvioAsync(Npce_WinClient.Test.References.Vol.InvioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/Conferma", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/ConfermaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WatermarkObject))]
        Npce_WinClient.Test.References.Vol.ConfermaResult Conferma(Npce_WinClient.Test.References.Vol.ConfermaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/Conferma", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/ConfermaResponse")]
        System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.ConfermaResult> ConfermaAsync(Npce_WinClient.Test.References.Vol.ConfermaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaCamereDiCommercio", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaCamereDiCommercioRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WatermarkObject))]
        Npce_WinClient.Test.References.Vol.RecuperaCamereDiCommercioResult RecuperaCamereDiCommercio(Npce_WinClient.Test.References.Vol.RecuperaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaCamereDiCommercio", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaCamereDiCommercioRespon" +
            "se")]
        System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaCamereDiCommercioResult> RecuperaCamereDiCommercioAsync(Npce_WinClient.Test.References.Vol.RecuperaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaTipiDocumenti", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaTipiDocumentiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WatermarkObject))]
        Npce_WinClient.Test.References.Vol.RecuperaTipiDocumentiResult RecuperaTipiDocumenti(Npce_WinClient.Test.References.Vol.RecuperaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaTipiDocumenti", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaTipiDocumentiResponse")]
        System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaTipiDocumentiResult> RecuperaTipiDocumentiAsync(Npce_WinClient.Test.References.Vol.RecuperaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaTipiDocumentiChiusure", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaTipiDocumentiChiusureRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WatermarkObject))]
        Npce_WinClient.Test.References.Vol.RecuperaTipiDocumentiChiusureResult RecuperaTipiDocumentiChiusure(Npce_WinClient.Test.References.Vol.RecuperaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaTipiDocumentiChiusure", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaTipiDocumentiChiusureRe" +
            "sponse")]
        System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaTipiDocumentiChiusureResult> RecuperaTipiDocumentiChiusureAsync(Npce_WinClient.Test.References.Vol.RecuperaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaMetodiRecapito", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaMetodiRecapitoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WatermarkObject))]
        Npce_WinClient.Test.References.Vol.RecuperaMetodiRecapitoResult RecuperaMetodiRecapito(Npce_WinClient.Test.References.Vol.RecuperaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaMetodiRecapito", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaMetodiRecapitoResponse")]
        System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaMetodiRecapitoResult> RecuperaMetodiRecapitoAsync(Npce_WinClient.Test.References.Vol.RecuperaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaIdRichiesta", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaIdRichiestaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WatermarkObject))]
        Npce_WinClient.Test.References.Vol.RecuperaIdRichiestaResult RecuperaIdRichiesta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaIdRichiesta", ReplyAction="http://ComunicazioniElettroniche.Visure.WS/Visure/RecuperaIdRichiestaResponse")]
        System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaIdRichiestaResult> RecuperaIdRichiestaAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class InvioRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RichiestaDocumenti documentiRequestField;
        
        private string idRichiestaField;
        
        private string clienteField;
        
        private bool controllaPrezzoDiVenditaField;
        
        private bool autoconfermaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RichiestaDocumenti DocumentiRequest {
            get {
                return this.documentiRequestField;
            }
            set {
                this.documentiRequestField = value;
                this.RaisePropertyChanged("DocumentiRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdRichiesta {
            get {
                return this.idRichiestaField;
            }
            set {
                this.idRichiestaField = value;
                this.RaisePropertyChanged("IdRichiesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ControllaPrezzoDiVendita {
            get {
                return this.controllaPrezzoDiVenditaField;
            }
            set {
                this.controllaPrezzoDiVenditaField = value;
                this.RaisePropertyChanged("ControllaPrezzoDiVendita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Autoconferma {
            get {
                return this.autoconfermaField;
            }
            set {
                this.autoconfermaField = value;
                this.RaisePropertyChanged("Autoconferma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class RichiestaDocumenti : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Richiedente richiedenteField;
        
        private RichiestaDocumento[] documentoField;
        
        private Recapito recapitoField;
        
        private string pDLField;
        
        private string identificativoRichiestaField;
        
        private decimal prezzoVenditaEuroIvaInclusaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Richiedente Richiedente {
            get {
                return this.richiedenteField;
            }
            set {
                this.richiedenteField = value;
                this.RaisePropertyChanged("Richiedente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Documento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public RichiestaDocumento[] Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Recapito Recapito {
            get {
                return this.recapitoField;
            }
            set {
                this.recapitoField = value;
                this.RaisePropertyChanged("Recapito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PDL {
            get {
                return this.pDLField;
            }
            set {
                this.pDLField = value;
                this.RaisePropertyChanged("PDL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdentificativoRichiesta {
            get {
                return this.identificativoRichiestaField;
            }
            set {
                this.identificativoRichiestaField = value;
                this.RaisePropertyChanged("IdentificativoRichiesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PrezzoVenditaEuroIvaInclusa {
            get {
                return this.prezzoVenditaEuroIvaInclusaField;
            }
            set {
                this.prezzoVenditaEuroIvaInclusaField = value;
                this.RaisePropertyChanged("PrezzoVenditaEuroIvaInclusa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class Richiedente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeField;
        
        private string cognomeField;
        
        private string indirizzoField;
        
        private string localitaField;
        
        private string cAPField;
        
        private string telefonoPrefissoField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
                this.RaisePropertyChanged("Cognome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("Indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Localita {
            get {
                return this.localitaField;
            }
            set {
                this.localitaField = value;
                this.RaisePropertyChanged("Localita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CAP {
            get {
                return this.cAPField;
            }
            set {
                this.cAPField = value;
                this.RaisePropertyChanged("CAP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TelefonoPrefisso {
            get {
                return this.telefonoPrefissoField;
            }
            set {
                this.telefonoPrefissoField = value;
                this.RaisePropertyChanged("TelefonoPrefisso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class RecuperaIdRichiestaResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDRichiestaField;
        
        private CEResult cEResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDRichiesta {
            get {
                return this.iDRichiestaField;
            }
            set {
                this.iDRichiestaField = value;
                this.RaisePropertyChanged("IDRichiesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CEResult CEResult {
            get {
                return this.cEResultField;
            }
            set {
                this.cEResultField = value;
                this.RaisePropertyChanged("CEResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.XOL")]
    public partial class CEResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class RecuperaMetodiRecapitoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MetodoRecapito[] dataSetField;
        
        private CEResult cEResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MetodoRecapito[] DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
                this.RaisePropertyChanged("DataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CEResult CEResult {
            get {
                return this.cEResultField;
            }
            set {
                this.cEResultField = value;
                this.RaisePropertyChanged("CEResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class MetodoRecapito : WatermarkObject {
        
        private string codiceField;
        
        private string nomeField;
        
        private string genereDocumentoCodiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GenereDocumentoCodice {
            get {
                return this.genereDocumentoCodiceField;
            }
            set {
                this.genereDocumentoCodiceField = value;
                this.RaisePropertyChanged("GenereDocumentoCodice");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MetodoRecapito))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentoChiusura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoDocumento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CameraDiCommercio))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class WatermarkObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long watermarkField;
        
        private System.DateTime validoDalField;
        
        private System.DateTime validoAlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Watermark {
            get {
                return this.watermarkField;
            }
            set {
                this.watermarkField = value;
                this.RaisePropertyChanged("Watermark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ValidoDal {
            get {
                return this.validoDalField;
            }
            set {
                this.validoDalField = value;
                this.RaisePropertyChanged("ValidoDal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ValidoAl {
            get {
                return this.validoAlField;
            }
            set {
                this.validoAlField = value;
                this.RaisePropertyChanged("ValidoAl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class DocumentoChiusura : WatermarkObject {
        
        private string codiceField;
        
        private string nomeField;
        
        private string descrizioneField;
        
        private int idGruppoField;
        
        private bool bolloObbligatorioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdGruppo {
            get {
                return this.idGruppoField;
            }
            set {
                this.idGruppoField = value;
                this.RaisePropertyChanged("IdGruppo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool BolloObbligatorio {
            get {
                return this.bolloObbligatorioField;
            }
            set {
                this.bolloObbligatorioField = value;
                this.RaisePropertyChanged("BolloObbligatorio");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class TipoDocumento : WatermarkObject {
        
        private string codiceField;
        
        private string nomeField;
        
        private string genereDocumentoCodiceField;
        
        private string cameraDiCommercioCodiceField;
        
        private decimal costoEuroField;
        
        private string descrizioneField;
        
        private bool ammetteNessunaChiusuraField;
        
        private bool ammetteNessunaChiusuraQuandoBolloField;
        
        private int idGruppoChiusureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GenereDocumentoCodice {
            get {
                return this.genereDocumentoCodiceField;
            }
            set {
                this.genereDocumentoCodiceField = value;
                this.RaisePropertyChanged("GenereDocumentoCodice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CameraDiCommercioCodice {
            get {
                return this.cameraDiCommercioCodiceField;
            }
            set {
                this.cameraDiCommercioCodiceField = value;
                this.RaisePropertyChanged("CameraDiCommercioCodice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal CostoEuro {
            get {
                return this.costoEuroField;
            }
            set {
                this.costoEuroField = value;
                this.RaisePropertyChanged("CostoEuro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AmmetteNessunaChiusura {
            get {
                return this.ammetteNessunaChiusuraField;
            }
            set {
                this.ammetteNessunaChiusuraField = value;
                this.RaisePropertyChanged("AmmetteNessunaChiusura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AmmetteNessunaChiusuraQuandoBollo {
            get {
                return this.ammetteNessunaChiusuraQuandoBolloField;
            }
            set {
                this.ammetteNessunaChiusuraQuandoBolloField = value;
                this.RaisePropertyChanged("AmmetteNessunaChiusuraQuandoBollo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdGruppoChiusure {
            get {
                return this.idGruppoChiusureField;
            }
            set {
                this.idGruppoChiusureField = value;
                this.RaisePropertyChanged("IdGruppoChiusure");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class CameraDiCommercio : WatermarkObject {
        
        private string codiceField;
        
        private string nomeField;
        
        private string provinciaSiglaField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProvinciaSigla {
            get {
                return this.provinciaSiglaField;
            }
            set {
                this.provinciaSiglaField = value;
                this.RaisePropertyChanged("ProvinciaSigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class RecuperaTipiDocumentiChiusureResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DocumentoChiusura[] dataSetField;
        
        private CEResult cEResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public DocumentoChiusura[] DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
                this.RaisePropertyChanged("DataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CEResult CEResult {
            get {
                return this.cEResultField;
            }
            set {
                this.cEResultField = value;
                this.RaisePropertyChanged("CEResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class RecuperaTipiDocumentiResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TipoDocumento[] dataSetField;
        
        private CEResult cEResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public TipoDocumento[] DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
                this.RaisePropertyChanged("DataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CEResult CEResult {
            get {
                return this.cEResultField;
            }
            set {
                this.cEResultField = value;
                this.RaisePropertyChanged("CEResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class RecuperaCamereDiCommercioResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CameraDiCommercio[] dataSetField;
        
        private CEResult cEResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public CameraDiCommercio[] DataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
                this.RaisePropertyChanged("DataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CEResult CEResult {
            get {
                return this.cEResultField;
            }
            set {
                this.cEResultField = value;
                this.RaisePropertyChanged("CEResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class RecuperaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long watermarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Watermark {
            get {
                return this.watermarkField;
            }
            set {
                this.watermarkField = value;
                this.RaisePropertyChanged("Watermark");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class ConfermaResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CEResult cEResultField;
        
        private string idOrdineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CEResult CEResult {
            get {
                return this.cEResultField;
            }
            set {
                this.cEResultField = value;
                this.RaisePropertyChanged("CEResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdOrdine {
            get {
                return this.idOrdineField;
            }
            set {
                this.idOrdineField = value;
                this.RaisePropertyChanged("IdOrdine");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.XOL")]
    public partial class DatiTransazione : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransazioneField;
        
        private string codiceAutorizzazioneField;
        
        private System.DateTime dataAutorizzazioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdTransazione {
            get {
                return this.idTransazioneField;
            }
            set {
                this.idTransazioneField = value;
                this.RaisePropertyChanged("IdTransazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodiceAutorizzazione {
            get {
                return this.codiceAutorizzazioneField;
            }
            set {
                this.codiceAutorizzazioneField = value;
                this.RaisePropertyChanged("CodiceAutorizzazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DataAutorizzazione {
            get {
                return this.dataAutorizzazioneField;
            }
            set {
                this.dataAutorizzazioneField = value;
                this.RaisePropertyChanged("DataAutorizzazione");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class ConfermaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OpzionePagamento opzionePagamentoField;
        
        private DatiTransazione datiTransazioneField;
        
        private string idOrdineField;
        
        private System.DateTime dataPagamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OpzionePagamento OpzionePagamento {
            get {
                return this.opzionePagamentoField;
            }
            set {
                this.opzionePagamentoField = value;
                this.RaisePropertyChanged("OpzionePagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DatiTransazione DatiTransazione {
            get {
                return this.datiTransazioneField;
            }
            set {
                this.datiTransazioneField = value;
                this.RaisePropertyChanged("DatiTransazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdOrdine {
            get {
                return this.idOrdineField;
            }
            set {
                this.idOrdineField = value;
                this.RaisePropertyChanged("IdOrdine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DataPagamento {
            get {
                return this.dataPagamentoField;
            }
            set {
                this.dataPagamentoField = value;
                this.RaisePropertyChanged("DataPagamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.XOL")]
    public partial class OpzionePagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool postFatturazioneField;
        
        private string descrizioneTipoPagamentoField;
        
        private string idTipoPagamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool PostFatturazione {
            get {
                return this.postFatturazioneField;
            }
            set {
                this.postFatturazioneField = value;
                this.RaisePropertyChanged("PostFatturazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DescrizioneTipoPagamento {
            get {
                return this.descrizioneTipoPagamentoField;
            }
            set {
                this.descrizioneTipoPagamentoField = value;
                this.RaisePropertyChanged("DescrizioneTipoPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdTipoPagamento {
            get {
                return this.idTipoPagamentoField;
            }
            set {
                this.idTipoPagamentoField = value;
                this.RaisePropertyChanged("IdTipoPagamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.XOL")]
    public partial class Totale : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valutaField;
        
        private string descrizioneField;
        
        private double importoTotaleField;
        
        private double importoNettoField;
        
        private double importoIvaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Valuta {
            get {
                return this.valutaField;
            }
            set {
                this.valutaField = value;
                this.RaisePropertyChanged("Valuta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double ImportoTotale {
            get {
                return this.importoTotaleField;
            }
            set {
                this.importoTotaleField = value;
                this.RaisePropertyChanged("ImportoTotale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double ImportoNetto {
            get {
                return this.importoNettoField;
            }
            set {
                this.importoNettoField = value;
                this.RaisePropertyChanged("ImportoNetto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double ImportoIva {
            get {
                return this.importoIvaField;
            }
            set {
                this.importoIvaField = value;
                this.RaisePropertyChanged("ImportoIva");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.XOL")]
    public partial class OggettoValorizzazione : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Totale totaleField;
        
        private string codiceMaterialeField;
        
        private string descrizioneCodiceMaterialeField;
        
        private double percentualeIvaField;
        
        private string codiceIvaField;
        
        private int quantitaField;
        
        private double importoUnitarioTotaleField;
        
        private double importoUnitarioNettoField;
        
        private double importoUnitarioIvaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Totale Totale {
            get {
                return this.totaleField;
            }
            set {
                this.totaleField = value;
                this.RaisePropertyChanged("Totale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodiceMateriale {
            get {
                return this.codiceMaterialeField;
            }
            set {
                this.codiceMaterialeField = value;
                this.RaisePropertyChanged("CodiceMateriale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DescrizioneCodiceMateriale {
            get {
                return this.descrizioneCodiceMaterialeField;
            }
            set {
                this.descrizioneCodiceMaterialeField = value;
                this.RaisePropertyChanged("DescrizioneCodiceMateriale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double PercentualeIva {
            get {
                return this.percentualeIvaField;
            }
            set {
                this.percentualeIvaField = value;
                this.RaisePropertyChanged("PercentualeIva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CodiceIva {
            get {
                return this.codiceIvaField;
            }
            set {
                this.codiceIvaField = value;
                this.RaisePropertyChanged("CodiceIva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Quantita {
            get {
                return this.quantitaField;
            }
            set {
                this.quantitaField = value;
                this.RaisePropertyChanged("Quantita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double ImportoUnitarioTotale {
            get {
                return this.importoUnitarioTotaleField;
            }
            set {
                this.importoUnitarioTotaleField = value;
                this.RaisePropertyChanged("ImportoUnitarioTotale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double ImportoUnitarioNetto {
            get {
                return this.importoUnitarioNettoField;
            }
            set {
                this.importoUnitarioNettoField = value;
                this.RaisePropertyChanged("ImportoUnitarioNetto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double ImportoUnitarioIva {
            get {
                return this.importoUnitarioIvaField;
            }
            set {
                this.importoUnitarioIvaField = value;
                this.RaisePropertyChanged("ImportoUnitarioIva");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.XOL")]
    public partial class Richiesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDRichiestaField;
        
        private string guidUtenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDRichiesta {
            get {
                return this.iDRichiestaField;
            }
            set {
                this.iDRichiestaField = value;
                this.RaisePropertyChanged("IDRichiesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GuidUtente {
            get {
                return this.guidUtenteField;
            }
            set {
                this.guidUtenteField = value;
                this.RaisePropertyChanged("GuidUtente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.XOL")]
    public partial class ValorizzazioneServizio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Richiesta richiestaField;
        
        private string iDServizioField;
        
        private int numeroPagineField;
        
        private OggettoValorizzazione[] oggettoValorizzazioneField;
        
        private Totale totaleField;
        
        private double impostaDiBolloField;
        
        private double importoTotaleConIdBField;
        
        private CEResult cEResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Richiesta Richiesta {
            get {
                return this.richiestaField;
            }
            set {
                this.richiestaField = value;
                this.RaisePropertyChanged("Richiesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IDServizio {
            get {
                return this.iDServizioField;
            }
            set {
                this.iDServizioField = value;
                this.RaisePropertyChanged("IDServizio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumeroPagine {
            get {
                return this.numeroPagineField;
            }
            set {
                this.numeroPagineField = value;
                this.RaisePropertyChanged("NumeroPagine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OggettoValorizzazione", Order=3)]
        public OggettoValorizzazione[] OggettoValorizzazione {
            get {
                return this.oggettoValorizzazioneField;
            }
            set {
                this.oggettoValorizzazioneField = value;
                this.RaisePropertyChanged("OggettoValorizzazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Totale Totale {
            get {
                return this.totaleField;
            }
            set {
                this.totaleField = value;
                this.RaisePropertyChanged("Totale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double ImpostaDiBollo {
            get {
                return this.impostaDiBolloField;
            }
            set {
                this.impostaDiBolloField = value;
                this.RaisePropertyChanged("ImpostaDiBollo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double ImportoTotaleConIdB {
            get {
                return this.importoTotaleConIdBField;
            }
            set {
                this.importoTotaleConIdBField = value;
                this.RaisePropertyChanged("ImportoTotaleConIdB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public CEResult CEResult {
            get {
                return this.cEResultField;
            }
            set {
                this.cEResultField = value;
                this.RaisePropertyChanged("CEResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.XOL")]
    public partial class Valorizzazione : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ValorizzazioneServizio[] valorizzazioneServizioField;
        
        private OpzionePagamento[] opzionePagamentoField;
        
        private Totale totaleField;
        
        private double impostaDiBolloField;
        
        private double importoTotaleConIdBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValorizzazioneServizio", Order=0)]
        public ValorizzazioneServizio[] ValorizzazioneServizio {
            get {
                return this.valorizzazioneServizioField;
            }
            set {
                this.valorizzazioneServizioField = value;
                this.RaisePropertyChanged("ValorizzazioneServizio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OpzionePagamento", Order=1)]
        public OpzionePagamento[] OpzionePagamento {
            get {
                return this.opzionePagamentoField;
            }
            set {
                this.opzionePagamentoField = value;
                this.RaisePropertyChanged("OpzionePagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Totale Totale {
            get {
                return this.totaleField;
            }
            set {
                this.totaleField = value;
                this.RaisePropertyChanged("Totale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double ImpostaDiBollo {
            get {
                return this.impostaDiBolloField;
            }
            set {
                this.impostaDiBolloField = value;
                this.RaisePropertyChanged("ImpostaDiBollo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double ImportoTotaleConIdB {
            get {
                return this.importoTotaleConIdBField;
            }
            set {
                this.importoTotaleConIdBField = value;
                this.RaisePropertyChanged("ImportoTotaleConIdB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class InvioResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CEResult cEResultField;
        
        private Valorizzazione valorizzazioneField;
        
        private string idOrdineField;
        
        private string identificativoRichiestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CEResult CEResult {
            get {
                return this.cEResultField;
            }
            set {
                this.cEResultField = value;
                this.RaisePropertyChanged("CEResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Valorizzazione Valorizzazione {
            get {
                return this.valorizzazioneField;
            }
            set {
                this.valorizzazioneField = value;
                this.RaisePropertyChanged("Valorizzazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdOrdine {
            get {
                return this.idOrdineField;
            }
            set {
                this.idOrdineField = value;
                this.RaisePropertyChanged("IdOrdine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdentificativoRichiesta {
            get {
                return this.identificativoRichiestaField;
            }
            set {
                this.identificativoRichiestaField = value;
                this.RaisePropertyChanged("IdentificativoRichiesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class Destinatario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeCognomeField;
        
        private string indirizzoField;
        
        private string localitaField;
        
        private string cAPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NomeCognome {
            get {
                return this.nomeCognomeField;
            }
            set {
                this.nomeCognomeField = value;
                this.RaisePropertyChanged("NomeCognome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("Indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Localita {
            get {
                return this.localitaField;
            }
            set {
                this.localitaField = value;
                this.RaisePropertyChanged("Localita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CAP {
            get {
                return this.cAPField;
            }
            set {
                this.cAPField = value;
                this.RaisePropertyChanged("CAP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class Recapito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Destinatario destinatarioField;
        
        private string emailField;
        
        private string faxField;
        
        private string tipoRecapitoCodiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Destinatario Destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
                this.RaisePropertyChanged("Destinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoRecapitoCodice {
            get {
                return this.tipoRecapitoCodiceField;
            }
            set {
                this.tipoRecapitoCodiceField = value;
                this.RaisePropertyChanged("TipoRecapitoCodice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class DocumentoChiusuraCodice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class Intestatario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeField;
        
        private string cognomeField;
        
        private string indirizzoField;
        
        private string ragioneSocialeField;
        
        private string numeroREAField;
        
        private string codiceFiscaleDittaIndividualeField;
        
        private string codiceFiscaleImpresaField;
        
        private System.DateTime dataDiNascitaField;
        
        private string comuneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
                this.RaisePropertyChanged("Cognome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("Indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RagioneSociale {
            get {
                return this.ragioneSocialeField;
            }
            set {
                this.ragioneSocialeField = value;
                this.RaisePropertyChanged("RagioneSociale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroREA {
            get {
                return this.numeroREAField;
            }
            set {
                this.numeroREAField = value;
                this.RaisePropertyChanged("NumeroREA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodiceFiscaleDittaIndividuale {
            get {
                return this.codiceFiscaleDittaIndividualeField;
            }
            set {
                this.codiceFiscaleDittaIndividualeField = value;
                this.RaisePropertyChanged("CodiceFiscaleDittaIndividuale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodiceFiscaleImpresa {
            get {
                return this.codiceFiscaleImpresaField;
            }
            set {
                this.codiceFiscaleImpresaField = value;
                this.RaisePropertyChanged("CodiceFiscaleImpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DataDiNascita {
            get {
                return this.dataDiNascitaField;
            }
            set {
                this.dataDiNascitaField = value;
                this.RaisePropertyChanged("DataDiNascita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
                this.RaisePropertyChanged("Comune");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ComunicazioniElettroniche.Visure.WS")]
    public partial class RichiestaDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Intestatario intestatarioField;
        
        private DocumentoChiusuraCodice[] chiusuraField;
        
        private string tipoDocumentoCodiceField;
        
        private string linguaCodiceField;
        
        private string genereDocumentoCodiceField;
        
        private string cameraDiCommercioCodiceField;
        
        private string guidField;
        
        private int numeroCopieField;
        
        private bool bolloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Intestatario Intestatario {
            get {
                return this.intestatarioField;
            }
            set {
                this.intestatarioField = value;
                this.RaisePropertyChanged("Intestatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Chiusura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DocumentoChiusuraCodice[] Chiusura {
            get {
                return this.chiusuraField;
            }
            set {
                this.chiusuraField = value;
                this.RaisePropertyChanged("Chiusura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoDocumentoCodice {
            get {
                return this.tipoDocumentoCodiceField;
            }
            set {
                this.tipoDocumentoCodiceField = value;
                this.RaisePropertyChanged("TipoDocumentoCodice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LinguaCodice {
            get {
                return this.linguaCodiceField;
            }
            set {
                this.linguaCodiceField = value;
                this.RaisePropertyChanged("LinguaCodice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GenereDocumentoCodice {
            get {
                return this.genereDocumentoCodiceField;
            }
            set {
                this.genereDocumentoCodiceField = value;
                this.RaisePropertyChanged("GenereDocumentoCodice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CameraDiCommercioCodice {
            get {
                return this.cameraDiCommercioCodiceField;
            }
            set {
                this.cameraDiCommercioCodiceField = value;
                this.RaisePropertyChanged("CameraDiCommercioCodice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumeroCopie {
            get {
                return this.numeroCopieField;
            }
            set {
                this.numeroCopieField = value;
                this.RaisePropertyChanged("NumeroCopie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Bollo {
            get {
                return this.bolloField;
            }
            set {
                this.bolloField = value;
                this.RaisePropertyChanged("Bollo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VisureChannel : Npce_WinClient.Test.References.Vol.Visure, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisureClient : System.ServiceModel.ClientBase<Npce_WinClient.Test.References.Vol.Visure>, Npce_WinClient.Test.References.Vol.Visure {
        
        public VisureClient() {
        }
        
        public VisureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Npce_WinClient.Test.References.Vol.InvioResult Invio(Npce_WinClient.Test.References.Vol.InvioRequest request) {
            return base.Channel.Invio(request);
        }
        
        public System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.InvioResult> InvioAsync(Npce_WinClient.Test.References.Vol.InvioRequest request) {
            return base.Channel.InvioAsync(request);
        }
        
        public Npce_WinClient.Test.References.Vol.ConfermaResult Conferma(Npce_WinClient.Test.References.Vol.ConfermaRequest request) {
            return base.Channel.Conferma(request);
        }
        
        public System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.ConfermaResult> ConfermaAsync(Npce_WinClient.Test.References.Vol.ConfermaRequest request) {
            return base.Channel.ConfermaAsync(request);
        }
        
        public Npce_WinClient.Test.References.Vol.RecuperaCamereDiCommercioResult RecuperaCamereDiCommercio(Npce_WinClient.Test.References.Vol.RecuperaRequest request) {
            return base.Channel.RecuperaCamereDiCommercio(request);
        }
        
        public System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaCamereDiCommercioResult> RecuperaCamereDiCommercioAsync(Npce_WinClient.Test.References.Vol.RecuperaRequest request) {
            return base.Channel.RecuperaCamereDiCommercioAsync(request);
        }
        
        public Npce_WinClient.Test.References.Vol.RecuperaTipiDocumentiResult RecuperaTipiDocumenti(Npce_WinClient.Test.References.Vol.RecuperaRequest request) {
            return base.Channel.RecuperaTipiDocumenti(request);
        }
        
        public System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaTipiDocumentiResult> RecuperaTipiDocumentiAsync(Npce_WinClient.Test.References.Vol.RecuperaRequest request) {
            return base.Channel.RecuperaTipiDocumentiAsync(request);
        }
        
        public Npce_WinClient.Test.References.Vol.RecuperaTipiDocumentiChiusureResult RecuperaTipiDocumentiChiusure(Npce_WinClient.Test.References.Vol.RecuperaRequest request) {
            return base.Channel.RecuperaTipiDocumentiChiusure(request);
        }
        
        public System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaTipiDocumentiChiusureResult> RecuperaTipiDocumentiChiusureAsync(Npce_WinClient.Test.References.Vol.RecuperaRequest request) {
            return base.Channel.RecuperaTipiDocumentiChiusureAsync(request);
        }
        
        public Npce_WinClient.Test.References.Vol.RecuperaMetodiRecapitoResult RecuperaMetodiRecapito(Npce_WinClient.Test.References.Vol.RecuperaRequest request) {
            return base.Channel.RecuperaMetodiRecapito(request);
        }
        
        public System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaMetodiRecapitoResult> RecuperaMetodiRecapitoAsync(Npce_WinClient.Test.References.Vol.RecuperaRequest request) {
            return base.Channel.RecuperaMetodiRecapitoAsync(request);
        }
        
        public Npce_WinClient.Test.References.Vol.RecuperaIdRichiestaResult RecuperaIdRichiesta() {
            return base.Channel.RecuperaIdRichiesta();
        }
        
        public System.Threading.Tasks.Task<Npce_WinClient.Test.References.Vol.RecuperaIdRichiestaResult> RecuperaIdRichiestaAsync() {
            return base.Channel.RecuperaIdRichiestaAsync();
        }
    }
}
