// <auto-generated />
namespace NPCE_WinClient.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AmbienteId2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AmbienteId2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191803514_AmbienteId2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
