// <auto-generated />
namespace NPCE_WinClient.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Bollettini4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bollettini4));
        
        string IMigrationMetadata.Id
        {
            get { return "202004022147287_Bollettini4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
